services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=store.settings
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=store_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
  media: